### ISSUE TITLE
does the model support streaming SEANet?

### ISSUE THREAD

**Issue by andrewmabc** [zeroone-universe/RealTimeBWE#3]
I have read your code, where self.generator = SEANet(min_dim = 8, causality = True). But you haven't implemented streaming SEANet. I guess the generator is a offline SEANet.

google has implemented streaming mode for SEANet:
https://github.com/google-research/google-research/tree/master/kws_streaming

Do you have plan to implement streaming SEANet in pytorch-lightning?

Thanks!

**Comment by tea6329714** [comment]
"The author has implemented the causal sea-net. For streaming applications, you must add the so-called cache/memory/states/history to each convolutional-based operation in order to achieve frame-wise inference equivalent to sequence-wise inference (also known as offline)."

**Comment by zeroone-universe** [comment]
Hi, thank you for your interest in this repository. I am currently working on projects that are unrelated to the topic of this model, so I do not anticipate any updates to this repository shortly.
