### ISSUE TITLE
About the training result

### ISSUE THREAD

**Issue by yezhangyinge** [zeroone-universe/RealTimeBWE#4]
Hello! Thanks for your work. Could you tell me the result of your reproduction of this paper? Thanks!

**Comment by zeroone-universe** [comment]
Hi, thanks for your interest.  It's been a while so my memory is a bit hazy, but I trained the model using a different dataset than the one used in the paper and obtained results similar to the table presented in the paper. You may listen to some demo files presented in this repo. Thanks.

**Comment by yezhangyinge** [comment]
Thanks for your reply! I will listen to the demo files in this repo.
